HardwareStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('main.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"


urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("products/", views.products, name="products"),
    path('register/', views.register, name='register'),
    path("login", views.login_request, name ="login"),
    path("logout", views.logout_request, name= "logout"),
    path("user", views.userpage, name = "userpage"),
    path('search/', views.search_view, name='search'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db.models import Sum

class Product(models.Model):
	product_name = models.CharField(max_length=150)
	product_type = models.CharField(max_length=25)
	product_description = models.TextField()
	affiliate_url = models.SlugField(blank=True, null=True)
	product_image = models.ImageField(upload_to='images/')
	pricing_average = models.DecimalField(default=0, max_digits=3, decimal_places=1)
	performance_average = models.DecimalField(default=0, max_digits=3, decimal_places=1)
	durability_average = models.DecimalField(default=0, max_digits=3, decimal_places=1)


	def __str__(self):
		return self.product_name

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	products = models.ManyToManyField(Product)

	@receiver(post_save, sender=User) #add this
	def create_user_profile(sender, instance, created, **kwargs):
		if created:
			Profile.objects.create(user=instance)

	@receiver(post_save, sender=User) #add this
	def save_user_profile(sender, instance, **kwargs):
		instance.profile.save()

class Vote(models.Model):   #add this class and the following fields
	profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	pricing = models.IntegerField(default=0)
	performance = models.IntegerField(default=0)
	durability = models.IntegerField(default=0)

	def calculate_averages(self):
			product = self.product
			vote_qs = Vote.objects.filter(product=product)
			vote_count = vote_qs.count()
			pricing_total = vote_qs.aggregate(Sum('pricing'))
			performance_total = vote_qs.aggregate(Sum('performance'))
			durability_total = vote_qs.aggregate(Sum('durability'))
			product.pricing_average = pricing_total['pricing__sum']/vote_count
			product.performance_average = performance_total['performance__sum']/vote_count
			product.durability_average = durability_total['durability__sum']/vote_count
			product.save()

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Vote
from django.forms.widgets import NumberInput

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ('products',)

class VoteForm(forms.ModelForm):
	pricing = forms.IntegerField(widget=NumberInput(attrs={'placeholder': ('5'),'type':'range', 'min': '1', 'max': '10', 'class': 'pricing'}))
	performance = forms.IntegerField(widget=NumberInput(attrs={'placeholder': ('5'),'type':'range', 'min': '1', 'max': '10', 'class': 'performance'}))
	durability = forms.IntegerField(widget=NumberInput(attrs={'placeholder': ('5'),'type':'range', 'min': '1', 'max': '10', 'class': 'durability'}))

	class Meta:
		model = Vote
		fields = ('pricing', 'performance', 'durability')

class SearchForm(forms.Form):
    search_term = forms.CharField(max_length=100, required=True)
    category_choices = [
        ('', 'All Categories'),
        ('category1', 'Category 1'),
        ('category2', 'Category 2'),
    ]
    category = forms.ChoiceField(choices=category_choices, required=False)

main/views.py
from .models import Product
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from .forms import NewUserForm, UserForm, ProfileForm, VoteForm
from django.shortcuts import render, redirect
from .forms import SearchForm
from django.db.models import Q

def homepage(request):
	if request.method == "POST":
		product_id = request.POST.get('product_pk')
		product = Product.objects.get(id = product_id)
		request.user.profile.products.add(product)
		messages.success(request,(f'{product} added to wishlist.'))
		return redirect ('main:homepage')
	product = Product.objects.all()[:4]
	return render(request=request, template_name="main/home.html", context={'product':product})


def products(request):
	if request.method == "POST":
		if "score_submit" in request.POST:
			vote_form = VoteForm(request.POST)
			if vote_form.is_valid():
				form = vote_form.save(commit=False)
				form.profile = request.user.profile
				product_id = request.POST.get("product")
				form.product = Product.objects.get(id=product_id)
				form.save()
				form.calculate_averages()
				messages.success(request,(f'{form.product} product score submitted.'))
				return redirect ("main:products")
			messages.error(request,('Form is invalid.'))
			return redirect ("main:products")
		product_id = request.POST.get("product_pk")
		product = Product.objects.get(id = product_id)
		request.user.profile.products.add(product)
		messages.success(request,(f'{product} added to wishlist.'))
		return redirect ('main:products')
	product = Product.objects.all()
	paginator = Paginator(product, 18)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	vote_form = VoteForm()
	return render(request = request, template_name="main/products.html", context = {"product":product, "page_obj":page_obj, "vote_form":vote_form})


def register(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			return redirect("main:homepage")
	form = NewUserForm
	return render (request=request, template_name="main/register.html", context={"form":form})


def register(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("main:homepage")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm
	return render (request=request, template_name="main/register.html", context={"form":form})


def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("main:homepage")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="main/login.html", context={"form":form})


def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.")
	return redirect("main:homepage")


def userpage(request):
	if request.method == "POST":
		user_form = UserForm(request.POST, instance=request.user)
		profile_form = ProfileForm(request.POST, instance=request.user.profile)
		if user_form.is_valid():
			user_form.save()
			messages.success(request,('Your profile was successfully updated!'))
		elif profile_form.is_valid():
			profile_form.save()
			messages.success(request,('Your wishlist was successfully updated!'))
		else:
			messages.error(request,('Unable to complete request'))
		return redirect ("main:userpage")
	user_form = UserForm(instance=request.user)
	profile_form = ProfileForm(instance=request.user.profile)
	return render(request = request, template_name ="main/user.html", context = {"user":request.user,
		"user_form": user_form, "profile_form": profile_form })


def search_view(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            search_term = form.cleaned_data['search_term']
            category = form.cleaned_data['category']
            if category:
                products = Product.objects.filter(Q(product_name__icontains=search_term) | Q(product_type__icontains=search_term), product_type=category)
            else:
                products = Product.objects.filter(Q(product_name__icontains=search_term) | Q(product_type__icontains=search_term))
            context = {'products': products}
            return render(request, 'main/search_results.html', context)
    else:
        form = SearchForm()
    return render(request, 'main/search.html', {'form': form})

main/templates/main/header.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PC Hardware Store</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>

    {% include 'main/includes/messages.html' %}

    {% include 'main/includes/navbar.html' %}

    {% block content %}

    {% load static %}

    {% endblock %}

    {% include "main/includes/footer.html" %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/home.html
{% extends 'main/header.html' %}

  {% block content %}

  {% load static %}



  <!--CTA-->
  <div class="container py-5">
    <div class="row">
      <div class="col-sm-12 col-md-12 col-lg-6 pb-4">
        <h1 class="display-4 font-weight-bold">New Arrivals!</h1>
        <h5>Freshly announced hardware only in our store.</h5>
        {% if user.is_authenticated %}
            <a class="btn btn-primary mt-2" href="/user">VIEW WISHLIST</a>
          {% else %}
            <a class="btn btn-primary mt-2" href="/products">BROWSE</a>
          {% endif %}
      </div>
      <div class="col-sm-12 col-md-12 col-lg-6">
        <img class="img-fluid rounded" src="{% static 'img/home.png' %}" alt="home">
      </div>
    </div>
  </div>

 <div class="container py-3">
    <h2>Products</h2>
    <hr>
    <br>
    <div class="row">
      {% for p in product %}
        <div class="col-sm-12 col-md-6 col-lg-3 pb-4">
          <div class="card h-100" style="border:none">
            <img src="{{ p.product_image.url }}" class="card-img-top" alt="{{ p.product_name }}" style="width: auto; height: 250px; object-fit: scale-down;">
            <div class="card-body">
              <h5 class="card-title">{{ p.product_name }}</h5>
              <p class="card-text text-muted" style="font-size:12px">{{ p.product_type }}</p>
              <p class="card-text">{{ p.product_description }}</p>
              <p class="text-muted" style="font-size:12px">Pricing: {{ p.pricing_average }} | Performance: {{ p.performance_average }} | Durability: {{ p.durability_average }}</p>
              <div class="row">
                <div class="col-6 text-right">
                  <a href="{{ p.affiliate_url }}" class="btn btn-warning">Buy now</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
		</div>
		<div class="container text-right">
			<a href="/products">View more</a>
		</div>
	</div>

  {% endblock %}

main/templates/main/login.html
{% extends "main/header.html" %}

	{% block content %}

	{% load crispy_forms_tags %}

	<div class="container py-5">
	    <h1 class="font-weight-bold">Login</h1>
	    <hr>
	    <br>
		<form method="POST">
			{% csrf_token %}
			{{ form|crispy }}
			<br>
			<button class="btn btn-primary" type="submit">Login</button>
		</form>
		<br><br>
	</div>

	{% endblock %}

main/templates/main/products.html
{% extends "main/header.html" %}

    {% block content %}

    {% load crispy_forms_tags %}

    {% load static %}
    <!--Products-->
    <div class="container py-5">
        <h1 class="font-weight-bold">Products</h1>
        <hr>
        <br>
        <div class="row">
             {% for p in page_obj %}
                <div class="col-sm-12 col-md-6 col-lg-4 pb-4">
                    <div class="card h-100" style="border:none">
                        <img src="{{ p.product_image.url }}" class="card-img-top" alt="{{ p.product_name }}" style="width: auto; height: 200px; object-fit: scale-down;">
                        <div class="card-body">
                            <h5 class="card-title">{{ p.product_name }}</h5>
                            <p class="card-text text-muted" style="font-size:12px">{{ p.product_type }}</p>
                            <p class="card-text">{{ p.product_description }}</p>
                            <p class="text-muted" style="font-size:12px">Pricing: {{ p.pricing_average }} | Performance: {{ p.performance_average }} | Durability: {{ p.durability_average }}</p>
							<div class="row">
                                <div class="col-3 text-center">
                                    {% if user.is_authenticated %}
                                        <form method="post">
                                            {% csrf_token %}
                                            <input type="hidden" value="{{p.pk}}" name="product_pk">
                                            <button type="submit" class="btn btn-outline-primary" style="font-size:18px; border-radius: 50%">★</button>
                                        </form>
                                    {% else %}
                                        <a href="/register" class="btn btn-outline-primary" style="font-size:18px; border-radius: 50%">★</a>
                                    {% endif %}
                                </div>
                                <div class="col-4 text-center">
                                    <a class="btn btn-outline-primary" data-toggle="collapse" href="#collapse{{p.pk}}" role="button" aria-expanded="false" aria-controls="collapse{{p.pk}}">Review</a>
                                </div>
                                <div class="col-5 text-center">
                                    <a href="{{ p.affiliate_url }}" class="btn btn-warning">Buy now</a>
                                </div>
                            </div>
                        </div>
                        <div class="collapse" id="collapse{{p.pk}}">
							<div class="card card-body shadow">
								<h6>Product Score: {{ p.product_name }}</h6>
								<hr>
								<form method="post">
									{% csrf_token %}
									{% for field in vote_form %}
										<div class="row">
											<div class="col-10" id="slider_{{field.name}}_{{p.pk}}" onclick="sliderUpdate('{{field.name}}', {{p.pk}})">{{field|as_crispy_field}}</div>
											<div class="col-2 my-auto">
												<h6 class="text-center"><span id="score_{{field.name}}_{{p.pk}}" class=text-primary>5</span></h6>
											</div>
										</div>
									{% endfor %}
                                    <div class="text-right">
										{% if user.is_authenticated %}
											<input type="hidden" value="{{p.pk}}" name="product">
											<button type="submit" name="score_submit" class="btn btn-outline-primary">Submit Score</button>
										{% else %}
											<a href="/register" class="btn btn-outline-primary">Register</a>
										{% endif %}
									</div>
								</form>
							</div>
						</div>
                    </div>
                </div>
            {% endfor %}
        </div>

    <script>
        function sliderUpdate(field, pk) {
            document.getElementById("score_" + field + "_" + pk).innerText = document.getElementById("slider_" + field + "_" + pk).getElementsByClassName(field)[0].value ;
        }
    </script>

    <style>
        #id_pricing, #id_performance, #id_durability {
            -webkit-appearance: none;
            width: 100%;
            border-radius: 0px;
            height: 25px;
            background: #ffff;
            outline: none;
            opacity: 1;
            -webkit-transition: .2s;
            transition: opacity .2s;
        }

        #id_pricing::-webkit-slider-runnable-track, #id_performance::-webkit-slider-runnable-track, #id_durability::-webkit-slider-runnable-track {
          -webkit-appearance: none;
          width: 100%;
          height: 15px;
          border-radius: 0px;
          background: #fff;
          outline: none;
          opacity: 1;
          -webkit-transition: .2s;
          transition: opacity .2s;
      }


      #id_pricing::-webkit-slider-thumb, #id_performance::-webkit-slider-thumb, #id_durability::-webkit-slider-thumb {
        -webkit-appearance: none;
        border-radius: 0px;
        appearance: none;
        width: 25px;
        height: 25px;
        background: #007bff;
        cursor: pointer;
    }


    #id_pricing::-moz-range-thumb, #id_performance::-moz-range-thumb, #id_durability::-moz-range-thumb {
        -webkit-appearance: none;
        border-radius:0px;
        width: 25px;
        height: 25px;
        background: #007bff;
        cursor: pointer;
    }

    #id_pricing::-moz-range-track, #id_performance::-moz-range-track, #id_durability::-moz-range-track {
        -webkit-appearance: none;
        border-radius:0px;
        width: 25px;
        height: 25px;
        background: #007bff;
        cursor: pointer;
    }
</style>

        <!--Pagination-->
        <div class="container">
            <div class="pagination justify-content-center">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>

    </div>

    {% endblock %}

main/templates/main/register.html
{% extends "main/header.html" %}

	{% block content %}

	{% load crispy_forms_tags %}

	<div class="container py-5">
	    <h1 class="font-weight-bold">Register</h1>
	    <hr>
	    <br>
		<form method="POST">
			{% csrf_token %}
			{{ form | crispy }}
			<br>
			<button class="btn btn-primary" type="submit">Register</button>
		</form>
		<br><br>
		<p>If you already have an account, <a href="/login">login</a> instead.</p>
	</div>

	{% endblock %}

main/templates/main/results.html
{% extends 'main/header.html' %}

{% block content %}
  <h1>Search Results for "{{ query }}"</h1>
  <ul>
    {% for product in page_obj%}
    <li><a href="{% url 'product_name' product.id %}">{{ product.name }}</a></li>
    {% empty %}
    <li>No products found.</li>
    {% endfor %}
  </ul>
{% endblock %}

main/templates/main/search.html
{% extends "main/header.html" %}

{% block content %}
  <div class="container py-5">
    <h1 class="font-weight-bold">Please Input a Product or a Category into the searchbar above!</h1>
    <hr>
    <br>
  </div>
{% endblock %}

main/templates/main/search_results.html
{% extends "main/header.html" %}

{% load crispy_forms_tags %}

{% load static %}

{% block content %}
  <h1>Search Results</h1>
  {% if products %}
    <div class="row">
      {% for product in products %}
        <div class="col-sm-12 col-md-6 col-lg-4 pb-4">
          <div class="card h-100" style="border:none">
            <img src="{{ product.product_image.url }}" class="card-img-top" alt="{{ product.product_name }}" style="width: auto; height: 200px; object-fit: scale-down;">
            <div class="card-body">
              <h5 class="card-title">{{ product.product_name }}</h5>
              <p class="card-text text-muted" style="font-size:12px">{{ product.product_type }}</p>
              <p class="card-text">{{ product.product_description }}</p>
              <p class="text-muted" style="font-size:12px">Pricing: {{ product.pricing_average }} | Performance: {{ product.performance_average }} | Durability: {{ product.durability_average }}</p>
              <div class="row">
                <div class="col-3 text-center">
                  {% if user.is_authenticated %}
                    <form method="post">
                      {% csrf_token %}
                      <input type="hidden" value="{{ product.pk }}" name="product_pk">
                      <button type="submit" class="btn btn-outline-primary" style="font-size:18px; border-radius: 50%">★</button>
                    </form>
                  {% else %}
                    <a href="/register" class="btn btn-outline-primary" style="font-size:18px; border-radius: 50%">★</a>
                  {% endif %}
                </div>
                <div class="col-4 text-center">
                  <a class="btn btn-outline-primary" data-bs-toggle="collapse" href="#collapse{{ product.pk }}" role="button" aria-expanded="false" aria-controls="collapse{{ product.pk }}">Review</a>
                </div>
                <div class="col-5 text-center">
                  <a href="{{ product.affiliate_url }}" class="btn btn-warning">Buy now</a>
                </div>
              </div>
            </div>
            <div class="collapse" id="collapse{{ product.pk }}">
              <div class="card card-body shadow">
                <h6>Product Score: {{ product.product_name }}</h6>
                <hr>
                <form method="post">
                  {% csrf_token %}
                  {% for field in vote_form %}
                    <div class="row">
                      <div class="col-10" id="slider_{{ field.name }}_{{ product.pk }}" onclick="sliderUpdate('{{ field.name }}', {{ product.pk }})">{{ field|as_crispy_field }}</div>
                      <div class="col-2 my-auto">
                        <h6 class="text-center"><span id="score_{{ field.name }}_{{ product.pk }}" class="text-primary">5</span></h6>
                      </div>
                    </div>
                  {% endfor %}
                  <div class="text-right">
                    {% if user.is_authenticated %}
                      <input type="hidden" value="{{ product.pk }}" name="product">
                      <button type="submit" name="score_submit" class="btn btn-outline-primary">Submit Score</button>
                    {% else %}
                      <a href="/register" class="btn btn-outline-primary">Register</a>
                    {% endif %}
                  </div>
                </form>
              </div>
            </div>
          </div>
          </div>
  {% endfor %}
</div>
{% else %}
  <p>No products found.</p>
{% endif %}
{% endblock %}

main/templates/main/user.html
{% extends "main/header.html" %}

	{% block content %}

	{% load crispy_forms_tags %}

	<br><br>
	<div class="container mx-auto">
	    <div class="row">
	    	<div class="col-sm-12 col-md-12 col-lg-3 pb-4">
		    	<div class="card p-4">
			    	<h4 class="card-title font-weight-bold text-center">Hello, {{ user.username|title }}</h4>
			      	<hr>
			    	<div class="card-text">
			    		<p class="text-muted mb-0" style="font-size: 12px">Username:</p>
			    		<p>{{ user.username }}</p>
			    		<p class="text-muted mb-0" style="font-size: 12px">Name:</p>
				  		<p>{{ user.first_name }} {{ user.last_name }}</p>
				  		<p class="text-muted mb-0" style="font-size: 12px">Email:</p>
				  		<p>{{ user.email }} </p>
						<div class="text-right">
							<button type="button" class="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#profileModal">Edit Profile</button>
						</div>
			        </div>
		    	</div>
		  	</div>
		    <div class="col-sm-12 col-md-12 col-lg-9 pb-4">
		    </div>
		</div>
	</div>

	<div class="modal fade" tabindex="-1" id="profileModal" role="dialog">
	  	<div class="modal-dialog" role="document">
		    <div class="modal-content">
		      	<div class="modal-header">
			        <h5 class="modal-title">Edit Profile</h5>
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			          <span aria-hidden="true">&times;</span>
			        </button>
		        </div>
		        <div class="modal-body">
			        <form method="post">
			          	{% csrf_token %}
			          	{{ user_form|crispy }}
					</form>
		        </div>
		      	<div class="modal-footer">
		        		<button type="submit" class="btn btn-primary">Save changes</button>
		        	</form>
		        	<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		        </div>
		    </div>
	  	</div>
	</div>

	<div class="container mx-auto">
	    <div class="row">
	    	<div class="col-sm-12 col-md-12 col-lg-3 pb-4">
		  	</div>
		    <div class="col-sm-12 col-md-12 col-lg-9 pb-4">
		    	<div class="row">
		    		<div class="col-6">
		    			<h2 class="font-weight-bold pt-4">Wishlist</h2>
		    		</div>
		    	</div>
		      	<br>
		      	<div class="row">
			      	{% for p in user.profile.products.all %}
				    	<div class="col-sm-12 col-md-6 col-lg-4 pb-4">
			                <div class="h-100">
			                	<img src="{{ p.product_image.url }}" class="card-img-top" alt="{{ p.product_name }}" style="width: auto; height: 225px; object-fit: scale-down;">
			                	<div class="card-body">
			                  		<h5 class="card-title">{{ p.product_name }}</h5>
			                    	<p class="card-text text-muted" style="font-size:12px">{{ p.product_type }}</p>
			                    	<a href="{{ p.affiliate_url }}" class="btn btn-warning">Buy now</a>
			                	</div>
			              	</div>
			            </div>
			    	{% endfor %}
		        </div>
		    </div>
		</div>
	</div>


<div class="modal fade" tabindex="-1" id="wishlistModal" role="dialog">
		<div class="modal-dialog" role="document">
		    <div class="modal-content">
		      	<div class="modal-header">
			        <h5 class="modal-title">Edit Profile</h5>
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			          <span aria-hidden="true">&times;</span>
			        </button>
		      	</div>
		      	<div class="modal-body">
			        <form method="post">
			        	{% csrf_token %}
					  	{{ profile_form|crispy }}
					  	<span class="text-muted" style="font-size:12px">Hold down "Control", or "Command" on a Mac, to select more than one.</span>
					</form>
		      	</div>
		      	<div class="modal-footer">
		        		<button type="submit" class="btn btn-primary">Save changes</button>
		        	</form>
		        	<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		      	</div>
		    </div>
	  	</div>
</div>

{% endblock %}