HardwareStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('main.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"


urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("products/", views.products, name="products"),
    path('register/', views.register, name='register'),
    path("login", views.login_request, name ="login"),
    path("logout", views.logout_request, name= "logout"),
    path("user", views.userpage, name = "userpage"),
    path('search/', views.search_view, name='search'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db.models import Sum

class Product(models.Model):
	product_name = models.CharField(max_length=150)
	product_type = models.CharField(max_length=25)
	product_description = models.TextField()
	affiliate_url = models.SlugField(blank=True, null=True)
	product_image = models.ImageField(upload_to='images/')
	pricing_average = models.DecimalField(default=0, max_digits=3, decimal_places=1)
	performance_average = models.DecimalField(default=0, max_digits=3, decimal_places=1)
	durability_average = models.DecimalField(default=0, max_digits=3, decimal_places=1)


	def __str__(self):
		return self.product_name

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	products = models.ManyToManyField(Product)

	@receiver(post_save, sender=User) #add this
	def create_user_profile(sender, instance, created, **kwargs):
		if created:
			Profile.objects.create(user=instance)

	@receiver(post_save, sender=User) #add this
	def save_user_profile(sender, instance, **kwargs):
		instance.profile.save()

class Vote(models.Model):   #add this class and the following fields
	profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	pricing = models.IntegerField(default=0)
	performance = models.IntegerField(default=0)
	durability = models.IntegerField(default=0)

	def calculate_averages(self):
			product = self.product
			vote_qs = Vote.objects.filter(product=product)
			vote_count = vote_qs.count()
			pricing_total = vote_qs.aggregate(Sum('pricing'))
			performance_total = vote_qs.aggregate(Sum('performance'))
			durability_total = vote_qs.aggregate(Sum('durability'))
			product.pricing_average = pricing_total['pricing__sum']/vote_count
			product.performance_average = performance_total['performance__sum']/vote_count
			product.durability_average = durability_total['durability__sum']/vote_count
			product.save()

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Vote
from django.forms.widgets import NumberInput

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ('products',)

class VoteForm(forms.ModelForm):
	pricing = forms.IntegerField(widget=NumberInput(attrs={'placeholder': ('5'),'type':'range', 'min': '1', 'max': '10', 'class': 'pricing'}))
	performance = forms.IntegerField(widget=NumberInput(attrs={'placeholder': ('5'),'type':'range', 'min': '1', 'max': '10', 'class': 'performance'}))
	durability = forms.IntegerField(widget=NumberInput(attrs={'placeholder': ('5'),'type':'range', 'min': '1', 'max': '10', 'class': 'durability'}))

	class Meta:
		model = Vote
		fields = ('pricing', 'performance', 'durability')

class SearchForm(forms.Form):
    search_term = forms.CharField(max_length=100, required=True)
    category_choices = [
        ('', 'All Categories'),
        ('category1', 'Category 1'),
        ('category2', 'Category 2'),
    ]
    category = forms.ChoiceField(choices=category_choices, required=False)

main/views.py
from .models import Product
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from .forms import NewUserForm, UserForm, ProfileForm, VoteForm
from django.shortcuts import render, redirect
from .forms import SearchForm
from django.db.models import Q

def homepage(request):
	if request.method == "POST":
		product_id = request.POST.get('product_pk')
		product = Product.objects.get(id = product_id)
		request.user.profile.products.add(product)
		messages.success(request,(f'{product} added to wishlist.'))
		return redirect ('main:homepage')
	product = Product.objects.all()[:4]
	return render(request=request, template_name="main/home.html", context={'product':product})


def products(request):
	if request.method == "POST":
		if "score_submit" in request.POST:
			vote_form = VoteForm(request.POST)
			if vote_form.is_valid():
				form = vote_form.save(commit=False)
				form.profile = request.user.profile
				product_id = request.POST.get("product")
				form.product = Product.objects.get(id=product_id)
				form.save()
				form.calculate_averages()
				messages.success(request,(f'{form.product} product score submitted.'))
				return redirect ("main:products")
			messages.error(request,('Form is invalid.'))
			return redirect ("main:products")
		product_id = request.POST.get("product_pk")
		product = Product.objects.get(id = product_id)
		request.user.profile.products.add(product)
		messages.success(request,(f'{product} added to wishlist.'))
		return redirect ('main:products')
	product = Product.objects.all()
	paginator = Paginator(product, 18)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	vote_form = VoteForm()
	return render(request = request, template_name="main/products.html", context = {"product":product, "page_obj":page_obj, "vote_form":vote_form})


def register(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			return redirect("main:homepage")
	form = NewUserForm
	return render (request=request, template_name="main/register.html", context={"form":form})


def register(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("main:homepage")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm
	return render (request=request, template_name="main/register.html", context={"form":form})


def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("main:homepage")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="main/login.html", context={"form":form})


def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.")
	return redirect("main:homepage")


def userpage(request):
	if request.method == "POST":
		user_form = UserForm(request.POST, instance=request.user)
		profile_form = ProfileForm(request.POST, instance=request.user.profile)
		if user_form.is_valid():
			user_form.save()
			messages.success(request,('Your profile was successfully updated!'))
		elif profile_form.is_valid():
			profile_form.save()
			messages.success(request,('Your wishlist was successfully updated!'))
		else:
			messages.error(request,('Unable to complete request'))
		return redirect ("main:userpage")
	user_form = UserForm(instance=request.user)
	profile_form = ProfileForm(instance=request.user.profile)
	return render(request = request, template_name ="main/user.html", context = {"user":request.user,
		"user_form": user_form, "profile_form": profile_form })


def search_view(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            search_term = form.cleaned_data['search_term']
            category = form.cleaned_data['category']
            if category:
                products = Product.objects.filter(Q(product_name__icontains=search_term) | Q(product_type__icontains=search_term), product_type=category)
            else:
                products = Product.objects.filter(Q(product_name__icontains=search_term) | Q(product_type__icontains=search_term))
            context = {'products': products}
            return render(request, 'main/search_results.html', context)
    else:
        form = SearchForm()
    return render(request, 'main/search.html', {'form': form})

main/templates/main/includes/footer.html
{% load static %}

<footer id="contact">
        <div class="container-fluid bg-dark text-light mt-5 pt-5">
            <div class="container py-5">
                <div class="row">
                    <div class="col-sm-12 col-md-3 col-lg-3">
                        <h6>Contact Us</h6>
                        <p class="font-weight-light">b.kochnev@acg.edu</p>
                    </div>
                    <div class="col-sm-12 col-md-3 col-lg-3">
                        <h6>Follow Us</h6>
                        <p class="font-weight-light">
                            <a href="#"><img src="{% static 'img/facebook.png' %}" alt="Facebook" class="img-fluid" style="width: auto; height: 30px; object-fit: scale-down;"></a>
                            <a href="#"><img src="{% static 'img/instagram.png' %}" alt="Instagram" class="img-fluid" style="width: auto; height: 30px; object-fit: scale-down;"></a>
                        </p>
                    </div>
                    <div class="col-sm-12 col-md-6 col-lg-6">
<h5>
                            <img src="{% static 'img/logo.jpg' %}" width="30" height="30" alt="logo">
                            PC Hardware Store
                        </h5>
                        <p style="font-size: 12px">We are proud to provide quality content and product information to our users. Our PC hardware store may earn a commission for purchases made through our product links. This helps us maintain the website and provide high-quality content and services to our customers. We only promote products that we believe in and use ourselves. Thank you for supporting our business."</p>
                    </div>
                </div>
                <div class="container text-center py-3">
                <p style="font-size:12px">Copyright © 2023 All Rights Belong to the original Owners.</p>
                </div>
            </div>
        </div>
    </footer>

main/templates/main/includes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

main/templates/main/includes/messages.html
<!--Messages-->

{% for message in messages %}

	<div class="container-fluid mx-0 p-0 sticky-top">
	  	<div class="alert {{ message.tags }} alert-dismissible m-0 p-3" role="alert">
		    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		    	<span aria-hidden="true">&times;</span>
		    </button>
	    	{{ message }}
	  	</div>
	</div>

{% endfor %}

main/templates/main/includes/navbar.html
{% load static %}

<script src=
"https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js">
    </script>

    <script src=
"https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js">
    </script>

    <link href=
"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-lightness/jquery-ui.css"
        rel="stylesheet" type="text/css" />

<nav class="navbar navbar-expand-sm navbar-light bg-light shadow">
 <a class="navbar-brand" href="/">
    Hardware Store
 </a>
 <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
 </button>
 <div class="collapse navbar-collapse" id="navbarText">
   <ul class="navbar-nav mr-auto">
     <li class="nav-item">
       <a class="nav-link" href="/products">Products</a>
     </li>
     <li class="nav-item">
            <a class="nav-link" href="#contact">Contact</a>
     </li>
   </ul>
     <ul class="navbar-nav mr-auto">
         <li class="nav-item">
         <form class="form-inline my-2 my-lg-0" action="{% url 'main:search' %}" method="post">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search_term">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
         </form>

     </ul>
     {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="/logout">Logout</a>
          </li>
          <li class="nav-item">
            <a class="btn btn-outline-primary" href="/user">{{user.username|title}}</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="/login">Login</a>
          </li>
          <li class="nav-item">
             <a class="btn btn-outline-primary" href="/register">Register</a>
          </li>
        {% endif %}
 </div>
</nav>